<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_template"
 *
 * Auto generated by Extension Builder 2018-12-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'RKW Template',
    'description' => 'Contains all configuration for the website',
    'category' => 'plugin',
    'author' => 'Steffen Kroggel',
    'author_email' => 'developer@steffenkroggel.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.40',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
            'gridelements' => '8.6.3-8.7.99',
            'rkw_authors'  => '8.7.0-8.7.99',
            'rkw_basics'  => '8.7.28-8.7.99',
            'rkw_etracker'  => '8.7.16-8.7.99',
            'rkw_events'  => '8.7.0-8.7.99',
            'rkw_pdf2content'  => '8.7.0-8.7.99',
            'rkw_projects' => '8.7.0-8.7.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];