<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_template"
 *
 * Auto generated by Extension Builder 2018-12-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'RKW Template',
    'description' => 'Contains all configuration for the website',
    'category' => 'plugin',
    'author' => 'Steffen Kroggel, Christian Dilger',
    'author_email' => 'developer@steffenkroggel.de, c.dilger@addorange.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'clearCacheOnLoad' => 0,
    'version' => '9.5.1004',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
            'gridelements' => '9.8.0-9.8.99',
            'ajax_api' => '9.5.0-10.4.99',
            'core_extended' => '9.5.4-10.4.99',
            'dr_seo' => '9.5.4-12.4.99',
            'accelerator' => '9.5.11-10.4.99',
            'fe_register' => '9.5.0-10.4.99',
            'rkw_alerts'  => '9.5.0-10.4.99',
            'rkw_authors'  => '9.5.0-10.4.99',
            'rkw_basics'  => '9.5.0-10.4.99',
            'rkw_etracker'  => '9.5.0-10.4.99',
            'rkw_events'  => '9.5.0-10.4.99',
            'rkw_pdf2content'  => '9.5.0-10.4.99',
            'rkw_projects' => '9.5.0-10.4.99',
            'rkw_related' => '9.5.0-10.4.99',
            'rkw_tools'  => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
