####
#  CKEditor configuration for rkw_template
###

# Load default processing options
imports:
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
  - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }
  - { resource: 'EXT:rkw_template/Themes/_Core/Configuration/TsConfig/RTE/Editor/Imports/Processing.yaml' }
  - { resource: 'EXT:rkw_template/Themes/_Core/Configuration/TsConfig/RTE/Editor/Imports/Toolbar.yaml' }
  - { resource: 'EXT:rkw_template/Themes/_Core/Configuration/TsConfig/RTE/Editor/Basics.yaml' }

# Add configuration for the editor
# For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config
editor:

  # see: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html
  config:

    # the CSS file to be used inside the editor
    contentsCss: "EXT:rkw_template/Themes/_Core/Resources/Public/css/rte.css"

    # block-formats available
    format_tags: 'p;h1;h2;h3;h4'

    stylesSet:
      # block level styles
      - { name: 'Tabelle Normal', element: 'table', attributes: { 'class': 'contenttable responsive' } }
      - { name: 'Tabelle Abwechselnd', element: 'table', attributes: { 'class': 'contenttable-1 responsive' } }

    justifyClasses:
      - align-left
      - align-center
      - align-right
      - align-justify