####
#  CKEditor configuration for rkw_template
###

# Load default processing options
imports:
  - { resource: 'EXT:rkw_template/Themes/_Core/Configuration/TsConfig/RTE/Editor/Default.yaml' }

# Add configuration for the editor
# For complete documentation see http://docs.ckeditor.com/#!/api/CKEDITOR.config
editor:

  # see: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html
  config:

    # the CSS file to be used inside the editor
    contentsCss: "EXT:rkw_template/Themes/WePstra/Resources/Public/css/rte.css"

    # see: https://ckeditor.com/latest/samples/toolbarconfigurator/index.html#advanced
    removeButtons:
      - Blockquote
      - Table
